### 2.3.1. Поэлементные операции

In [1]:
import numpy as np

In [2]:
def naive_relu(x):
    # убедиться, что х - двумерный массив
    assert len(x.shape) == 2

    # ислючить перезапись исходного вектора
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [3]:
x = np.array([[5, 78]])
x.shape

(1, 2)

In [4]:
print(naive_relu(x))

[[ 5 78]]


In [6]:
# сложение
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [11]:
a = np.array([[6, 8]])
b = np.array([[14, 6]])
print(naive_add(a, b))

[[20 14]]


In [15]:
# умножение
def naive_product(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] *= y[i, j]
    return x

In [16]:
c = np.array([[6, 8]])
d = np.array([[1, 6]])
print(naive_product(c, d))

[[ 6 48]]


### 2.3.3. Скалярное произведение тензоров
#### 1) Умножение векторов

In [21]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)
z

7.0900321562491735

In [23]:
def naive_vector_dot(x, y):
    # make sure x,y are NumPy vectors
    assert len(x.shape) == 1
    assert len(y.shape) == 1

    assert x.shape[0] == y.shape[0]
    z = 0.

    for k in range(x.shape[0]):
        z += x[k] * y[k]
    return z

In [25]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

result = naive_vector_dot(x, y)

print(result)  # Output: 32.0

32.0


Обратите внимание, что в результате скалярного произведения двух векторов получается скаляр и в операции могут участвовать только векторы с одинаковым количеством элементов.

#### 2) Скалярное умножение вектора на матрицу

In [27]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1.
    assert x.shape[1] == y.shape[0]

    z = np.zeros(x.shape[0])

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [28]:
r = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([1, 2, 3])

result = naive_matrix_vector_dot(r, e)

print(result)  # Output: [14. 32.]

[14. 32.]


The result is a 1-dimensional NumPy array.

In [30]:
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

In [31]:
result = naive_matrix_vector_dot(r, e)

print(result)  # Output: [14. 32.]

[14. 32.]
